// Builds the Chrome Web Store package.
//   node scripts/build-store.mjs --api-url https://agent.example.com [--version 1.0.1]
// - bakes the Infera Agent server into config.js, so every installed copy
//   shows the Infera Agent sign-in without any setup;
// - removes the development "key" from manifest.json (the store assigns the ID);
// - writes dist/infera-agent-<version>.zip, ready to upload.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { deflateRawSync, crc32 } from 'node:zlib';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const ext = path.join(root, 'extension');
const args = process.argv.slice(2);
const val = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : undefined; };

const apiUrl = (val('--api-url') || '').replace(/\/+$/, '');
if (!/^https:\/\/[^/]+/.test(apiUrl)) {
  console.error('Usage: node scripts/build-store.mjs --api-url https://<your Infera Agent server> [--version x.y.z]');
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(path.join(ext, 'manifest.json'), 'utf8'));
delete manifest.key;
if (val('--version')) manifest.version = val('--version');

const files = [];
const walk = (dir) => {
  for (const f of readdirSync(dir).sort()) {
    const p = path.join(dir, f);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
};
walk(ext);

const entries = files.map((abs) => {
  const rel = path.relative(ext, abs).split(path.sep).join('/');
  let data = readFileSync(abs);
  if (rel === 'manifest.json') data = Buffer.from(JSON.stringify(manifest, null, 2) + '\n');
  if (rel === 'config.js') {
    data = Buffer.from(`// Generated by scripts/build-store.mjs for the Chrome Web Store build.\nexport const INFERA_API_URL = ${JSON.stringify(apiUrl)};\n`);
  }
  return { rel, data };
});

// Minimal ZIP writer (deflate), enough for the store upload.
const parts = [];
const central = [];
let offset = 0;
const dosTime = 0x0000; const dosDate = 0x5a21; // fixed timestamp for reproducible builds
for (const { rel, data } of entries) {
  const name = Buffer.from(rel, 'utf8');
  const comp = deflateRawSync(data, { level: 9 });
  const crc = crc32(data) >>> 0;
  const local = Buffer.alloc(30);
  local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4); local.writeUInt16LE(0x0800, 6); local.writeUInt16LE(8, 8);
  local.writeUInt16LE(dosTime, 10); local.writeUInt16LE(dosDate, 12); local.writeUInt32LE(crc, 14);
  local.writeUInt32LE(comp.length, 18); local.writeUInt32LE(data.length, 22); local.writeUInt16LE(name.length, 26); local.writeUInt16LE(0, 28);
  parts.push(local, name, comp);
  const cen = Buffer.alloc(46);
  cen.writeUInt32LE(0x02014b50, 0); cen.writeUInt16LE(20, 4); cen.writeUInt16LE(20, 6); cen.writeUInt16LE(0x0800, 8); cen.writeUInt16LE(8, 10);
  cen.writeUInt16LE(dosTime, 12); cen.writeUInt16LE(dosDate, 14); cen.writeUInt32LE(crc, 16); cen.writeUInt32LE(comp.length, 20);
  cen.writeUInt32LE(data.length, 24); cen.writeUInt16LE(name.length, 28); cen.writeUInt32LE(offset, 42);
  central.push(cen, name);
  offset += local.length + name.length + comp.length;
}
const cenBuf = Buffer.concat(central);
const end = Buffer.alloc(22);
end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10);
end.writeUInt32LE(cenBuf.length, 12); end.writeUInt32LE(offset, 16);

const dist = path.join(root, 'dist');
mkdirSync(dist, { recursive: true });
const out = path.join(dist, `infera-agent-${manifest.version}.zip`);
writeFileSync(out, Buffer.concat([...parts, cenBuf, end]));
console.log(`Built ${path.relative(root, out)} — ${entries.length} files, server ${apiUrl}`);
console.log('Upload it at https://chrome.google.com/webstore/devconsole (see docs/PUBLISHING.md).');
